const AWS_REGION = 'eu-north-1'
const AWS_ACCESS_KEY_ID = 'AKIASFIXCTQJOP3YAAUY'
const AWS_SECRET_ACCESS_KEY = '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'

export { AWS_ACCESS_KEY_ID, AWS_REGION, AWS_SECRET_ACCESS_KEY }